Repository PaddlePaddle/CINN, pull requests merged in 2023-06, with the labels that each got.

#1491 op unittest for comparison op: equal/not_equal/greater_than/less_than/greater_equal/less_equal
  python/tests/ops/test_comparison_op.py
Labels: contributor, status: proposed

#1472 op unittets for top_k/transpose/triangular_solve
  cinn/hlir/op/contrib/sort.cc
  python/tests/ops/test_top_k_op.py
  python/tests/ops/test_transpose_op.py
  python/tests/ops/test_triangular_solve_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1488 op unittest for relu/reshape
  python/tests/ops/test_relu_op.py
  python/tests/ops/test_reshape_op.py
Labels: contributor, status: proposed

#1485 fix paddle test: arg_min/arg_max/flip/strided_slice
  cinn/frontend/op_mappers/paddle/arg_min_max.cc
  cinn/frontend/op_mappers/paddle/flip.cc
  cinn/hlir/op/transform.cc
  cinn/hlir/pe/transform.cc
  cinn/runtime/cuda/cinn_cuda_runtime_source.cuh
  cinn/runtime/cuda/cuda_instrinsics_float16.cc
Labels: contributor, status: proposed

#1484 Fix atan2
  cinn/frontend/op_mappers/paddle/atan.cc
  cinn/hlir/pe/broadcast.cc
  python/tests/op_mappers/test_atan2_op.py
  python/tests/ops/test_atan2_op.py
Labels: contributor, status: proposed

#1479 add op unitest for rsqrt
  python/tests/ops/test_rsqrt_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1477 Add op unitest for erf
  python/tests/ops/test_erf_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1399 Add gather tests
  python/tests/ops/test_gather_op.py
Labels: contributor, HappyOpenSource

#1492 Add op unitest for abs
  python/tests/ops/test_abs_op.py
Labels: contributor, status: proposed

#1483 Add unitest for is_inf/is_finite/is_nan
  python/tests/ops/test_is_finite_op.py
  python/tests/ops/test_is_inf_op.py
  python/tests/ops/test_is_nan_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1498 op unittest for clz/popc
  python/tests/ops/test_clz_op.py
  python/tests/ops/test_popc_op.py
Labels: contributor, status: proposed

#1500 op unittest for scatter_add, remove scatter/scatter_nd operator
  cinn/auto_schedule/measure/simple_runner.cc
  cinn/frontend/net_builder.cc
  cinn/frontend/net_builder_test.cc
  cinn/hlir/op/contrib/CMakeLists.txt
  cinn/hlir/op/contrib/scatter.cc
  cinn/hlir/op/contrib/scatter.h
  cinn/hlir/op/contrib/scatter_test.cc
  cinn/hlir/op/use_ops.h
  cinn/runtime/cuda/cinn_cuda_runtime_source.cuh
  cinn/runtime/cuda/cuda_intrinsics.cc
  python/tests/ops/test_scatter_add.py
Labels: contributor, status: proposed

#1499 Op gather support N-D index
  cinn/auto_schedule/tests/performance_comparison_test.cc
  cinn/frontend/net_builder.cc
  cinn/hlir/op/transform.cc
  cinn/hlir/pe/transform.cc
  python/tests/op_mappers/test_take_along_axis_op.py
Labels: contributor, status: proposed

#1471 Fix pool2d
  cinn/auto_schedule/tests/performance_comparison_test.cc
  cinn/frontend/net_builder.cc
  cinn/frontend/net_builder.h
  cinn/hlir/op/custom_call.cc
  cinn/hlir/op/nn.cc
  cinn/pybind/frontend.cc
  cinn/runtime/cuda/cuda_util.cc
  python/tests/op_mappers/test_pool2d_op.py
  python/tests/ops/test_pool2d_op.py
Labels: contributor, status: proposed

#1496 Add op unitest for negative
  python/tests/ops/test_negative_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1506 Add op unitest for trunc
  cinn/runtime/cuda/cinn_cuda_runtime_source.cuh
  cinn/runtime/cuda/cuda_intrinsics.cc
  python/tests/ops/test_trunc_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1511 Add op unitest for floor
  python/tests/ops/test_floor_op.py
Labels: contributor, status: proposed

#1509 Refactor op test on remainder, uniform and gaussian
  python/tests/ops/test_gaussian_random_op.py
  python/tests/ops/test_remainder_op.py
  python/tests/ops/test_uniform_random_op.py
Labels: contributor, status: proposed

#1495 op unittest for cbrt/ceil/cholesky/concat/constant/fill_constant
  cinn/frontend/net_builder.cc
  cinn/frontend/net_builder.h
  cinn/hlir/op/elementwise.cc
  cinn/pybind/frontend.cc
  python/tests/ops/test_cbrt_op.py
  python/tests/ops/test_ceil_op.py
  python/tests/ops/test_cholesky_op.py
  python/tests/ops/test_concat_op.py
  python/tests/ops/test_constant_op.py
  python/tests/ops/test_fill_constant_op.py
Labels: contributor, status: proposed

#1515 Refactor some op tests and fix bugs
  cinn/runtime/cuda/cinn_cuda_runtime_source.cuh
  python/tests/ops/test_depthwise_conv2d_op.py
  python/tests/ops/test_log_op.py
  python/tests/ops/test_round_op.py
Labels: contributor, status: proposed

#1514 op unittest for repeat/arange/reverse/elementwise_add_grad/flip
  cinn/frontend/net_builder.cc
  cinn/frontend/net_builder.h
  cinn/frontend/net_builder_test.cc
  cinn/hlir/op/contrib/CMakeLists.txt
  cinn/hlir/op/contrib/flip.cc
  cinn/hlir/op/contrib/flip.h
  cinn/hlir/op/contrib/flip_test.cc
  cinn/hlir/op/transform.cc
  cinn/hlir/op/use_ops.h
  cinn/pybind/frontend.cc
  python/tests/ops/op_test_helper.py
  python/tests/ops/test_add_op.py
  python/tests/ops/test_add_op_new.py
  python/tests/ops/test_arange_op.py
  python/tests/ops/test_repeat_op.py
  python/tests/ops/test_reverse_op.py
Labels: contributor, status: proposed

#1513 Refactor some op tests and fix bugs
  cinn/runtime/cpu/host_intrinsics.cc
  cinn/runtime/cpu/host_intrinsics.h
  cinn/runtime/cuda/cinn_cuda_runtime_source.cuh
  cinn/runtime/cuda/cuda_intrinsics.cc
  python/tests/ops/test_isclose_op.py
  python/tests/ops/test_logical_right_shift_op.py
  python/tests/ops/test_lookup_table_op.py
  python/tests/ops/test_pow_op.py
Labels: contributor, status: proposed

#1522 Fixed jitify commit to prevent header file conflicts
  cinn/hlir/op/contrib/repeat_test.cc
  cinn/lang/builtin.cc
  cinn/runtime/cuda/cuda_intrinsics.cc
  cmake/external/jitify.cmake
  python/tests/ops/test_floor_divide_op.py
  python/tests/ops/test_sign_op.py
Labels: contributor, status: proposed

#1501 Add Op UnitTest for one_hot
  python/tests/ops/test_one_hot_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1526 Update CMAKE_CXX_STANDARD to c++17
  CMakeLists.txt
  cinn/pybind/bind.h
  cmake/core.cmake
  cmake/external/absl.cmake
  tools/docker/Dockerfile.ci
  tools/docker/Dockerfile.ci.cuda
  tutorials/build_demo.sh
Labels: contributor, status: proposed

#1503 Add Op UnitTest for batchnorm
  python/tests/ops/test_batch_norm_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1531 Logical op full dtype support
  cinn/hlir/op/elementwise.cc
  cinn/hlir/pe/broadcast.cc
Labels: contributor, status: proposed

#1521 Add op unitest for acosh
  python/tests/ops/test_acosh_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1397 Add Op UniTest for logical_or
  python/tests/ops/test_logical_or_op.py
Labels: contributor, HappyOpenSource

#1534 Add Op UnitTest for logical_not
  python/tests/ops/test_logical_not_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1398 Add Op UniTest for logical_xor
  python/tests/ops/test_logical_xor_op.py
Labels: contributor, HappyOpenSource

#1396 Add Op UnitTest for logical_and
  python/tests/ops/test_logical_and_op.py
Labels: contributor, HappyOpenSource
