Repository PaddlePaddle/CINN, pull requests merged in 2023-05, with the labels that each got.

#1390 op unittest for scatter_assign
  python/tests/ops/test_scatter_assign_op.py
Labels: contributor, status: proposed

#1383 Add Op UnitTest for divide
  python/tests/ops/test_divide_op.py
Labels: contributor, status: proposed

#1381 Add Op UnitTest for Cast
  python/tests/ops/test_cast_op.py
Labels: contributor, status: proposed

#1387 Add Op UnitTest for floor_divide
  python/tests/ops/test_floor_divide_op.py
Labels: contributor, status: proposed

#1368 Update install.md
  docs/source/install.md
Labels: contributor, status: proposed

#1401 op unittest for select/sigmoid/sign/slice_assign/slice
  cinn/frontend/net_builder.h
  python/tests/ops/test_select_op.py
  python/tests/ops/test_sigmoid_op.py
  python/tests/ops/test_sign_op.py
  python/tests/ops/test_slice_assign_op.py
  python/tests/ops/test_slice_op.py
Labels: contributor, status: proposed

#1379 Add reduce test using new test helper
  cinn/frontend/net_builder.cc
  cinn/hlir/pe/ir_schedule_pe.cc
  python/tests/ops/test_reduce_op_new.py
  python/tests/ops/test_reduce_op_other.py
Labels: contributor, status: proposed

#1405 Fixed TestCaseHelper would exit after running one test class
  python/tests/ops/op_test_helper.py
  python/tests/ops/test_divide_op.py
  python/tests/ops/test_select_op.py
  python/tests/ops/test_slice_assign_op.py
  python/tests/ops/test_slice_op.py
Labels: contributor, status: proposed

#1384 Add Op UnitTest for expand_dims
  python/tests/ops/test_expand_dims.py
Labels: contributor, status: proposed

#1389 Add gather_nd tests
  python/tests/ops/test_gather_nd_op.py
Labels: contributor, status: proposed

#1421 cublas gemm support fp64
  cinn/runtime/cuda/cublas_util.h
  cinn/runtime/cuda/cuda_util.cc
  python/tests/ops/test_matmul_op.py
Labels: contributor, status: proposed

#1404 Op bitwise full type support
  cinn/frontend/pass/cast_collapsing_test.cc
  cinn/frontend/pass/dead_code_eliminate_test.cc
  cinn/frontend/pass/gemm_rewriter_test.cc
  cinn/frontend/pass/pass_test_helper.h
  cinn/frontend/pass/program_topoerror_test.cc
  cinn/frontend/pass/transpose_folding_input_test.cc
  cinn/frontend/pass/transpose_folding_output_test.cc
  cinn/frontend/pass/transpose_scale_folding_test.cc
  cinn/hlir/op/contrib/lookup_table_test.cc
  cinn/hlir/op/contrib/reciprocal_test.cc
  cinn/hlir/op/op_util.cc
  cinn/hlir/op/op_util.h
  cinn/hlir/pass/test_dot_merger.cc
  cinn/ir/ir_operators.cc
  cinn/optim/map_extern_call.cc
  cinn/pybind/common.cc
  cinn/pybind/frontend.cc
  cinn/runtime/cuda/cinn_cuda_runtime_source.cuh
  cinn/runtime/cuda/cuda_intrinsics.cc
  cinn/runtime/flags.cc
  cinn/runtime/flags.h
  python/tests/ops/test_bitwise_op.py
  python/tests/test_pe_elementwise.py
Labels: contributor, status: proposed

#1301 Op mapper scatter
  cinn/frontend/op_mappers/paddle/scatter.cc
  cinn/frontend/op_mappers/use_op_mappers.h
  cinn/hlir/op/op_util.cc
  cinn/hlir/op/transform.cc
  cinn/hlir/pe/transform.cc
  cinn/runtime/cuda/cinn_cuda_runtime_source.cuh
  cinn/runtime/cuda/cuda_instrinsics_float16.cc
  cinn/runtime/cuda/cuda_intrinsics.cc
  python/tests/op_mappers/test_scatter_op.py
  python/tests/ops/test_scatter_add.py
Labels: contributor

#1425 Fix typos
  cinn/auto_schedule/database/database.cc
  cinn/auto_schedule/measure/measure.h
  cinn/auto_schedule/measure/schedule_measurer.cc
  cinn/auto_schedule/search_space/block_sampler.cc
  cinn/auto_schedule/search_space/rule_sampler.cc
  cinn/auto_schedule/task/task_optimizer.cc
  cinn/auto_schedule/task/tune_task.cc
  cinn/auto_schedule/task_scheduler/task_scheduler.cc
  cinn/backends/codegen_c.cc
  cinn/backends/codegen_c.h
Labels: contributor, status: proposed

#1430 Add Op UniTest for acos
  python/tests/ops/test_acos_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1426 Add Op UnitTest for sin/cos/tan/sinh/cosh/tanh/asin
  cinn/runtime/cuda/cinn_cuda_runtime_source.cuh
  cinn/runtime/cuda/cuda_instrinsics_bfloat16.cc
  cinn/runtime/cuda/cuda_instrinsics_float16.cc
  python/tests/ops/test_asin_op.py
  python/tests/ops/test_cos_op.py
  python/tests/ops/test_cosh_op.py
  python/tests/ops/test_sin_op.py
  python/tests/ops/test_sinh_op.py
  python/tests/ops/test_tan_op.py
  python/tests/ops/test_tanh_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1446 Keep norm_grad dtype same as input dtype
  cinn/frontend/op_mappers/paddle/norm.cc
  python/tests/op_mappers/test_norm_op.py
Labels: contributor, status: proposed

#1454 Fix typos, affter to after
  cinn/hlir/pass/check_fusion_accuracy_pass_test.cc
Labels: contributor, status: proposed

#1455 Fix typos
  cinn/common/cas.cc
  cinn/common/cas.h
  cinn/frontend/decomposer/batch_norm_test.cc
  cinn/frontend/op_mappers/paddle/batchnorm.cc
  cinn/frontend/pass/cast_collapsing.cc
  cinn/hlir/op/elementwise.cc
  cinn/optim/buffer_assign.cc
  cinn/runtime/cinn_runtime.h
  cinn/utils/event.cc
  cmake/core.cmake
  docs/design.org
  infrt/common/axis.h
Labels: contributor, status: proposed

#1445 Update README.md
  README.md
Labels: contributor, status: proposed

#1453 op unittest for split
  python/tests/ops/test_split_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1411 op unittest for sort & enhance test helper
  cinn/hlir/op/contrib/argmax_test.cc
  cinn/hlir/op/contrib/argmin_test.cc
  cinn/hlir/op/contrib/sort.cc
  cinn/hlir/op/contrib/sort_test.cc
  cinn/runtime/cpu/host_intrinsics.cc
  cinn/runtime/cuda/cinn_cuda_runtime_source.cuh
  cinn/runtime/cuda/cuda_intrinsics.cc
  python/tests/ops/op_test_helper.py
  python/tests/ops/test_sort_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1464 Fix model convertor out of memory bug
  cinn/frontend/paddle_model_convertor.cc
  cinn/frontend/paddle_model_convertor.h
  cinn/pybind/frontend.cc
  python/tests/test_paddle_model_convertor.py
Labels: contributor, status: proposed

#1467 Add Op UnitTest for reciprocal
  python/tests/ops/test_reciprocal_op.py
Labels: contributor, status: proposed

#1380 Add Op UnitTest For broadcast_to
  python/tests/ops/test_broadcast_to_op_new.py
Labels: contributor, status: proposed, HappyOpenSource

#1457 op unittest for squeeze/subtract/sum
  cinn/hlir/op/elementwise.cc
  python/tests/ops/test_squeeze_op.py
  python/tests/ops/test_subtract_op.py
  python/tests/ops/test_sum_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1452 Add Op UniTest for atan atanh asinh
  python/tests/ops/test_asinh_op.py
  python/tests/ops/test_atan_op.py
  python/tests/ops/test_atanh_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1448 Add Op UnitTest for Sqrt
  python/tests/ops/test_sqrt_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1461 Fix typos
  cinn/auto_schedule/cost_model/feature.cc
  cinn/auto_schedule/cost_model/feature.h
  cinn/auto_schedule/cost_model/xgb_cost_model.h
  cinn/auto_schedule/database/database.h
  cinn/auto_schedule/database/jsonfile_database.cc
  cinn/auto_schedule/measure/simple_builder.cc
  cinn/auto_schedule/measure/simple_runner.cc
  cinn/auto_schedule/search_space/auto_gen_rule/auto_bind.cc
  cinn/auto_schedule/search_space/auto_gen_rule/auto_gen_rule.cc
  cinn/auto_schedule/search_space/auto_gen_rule/auto_gen_rule.h
  cinn/auto_schedule/search_space/auto_gen_rule/multi_level_tiling.cc
  cinn/auto_schedule/search_space/auto_gen_rule/multi_level_tiling.h
  cinn/auto_schedule/search_space/auto_gen_rule/test_helper.h
  cinn/auto_schedule/search_space/rule_sampler.h
  cinn/auto_schedule/search_space/search_space.cc
  cinn/auto_schedule/search_space/search_state.h
  cinn/auto_schedule/search_strategy/evolutionary_search.h
  cinn/auto_schedule/task/task_optimizer.cc
  cinn/auto_schedule/task/tune_task.h
  cinn/auto_schedule/tests/performance_comparison_test.cc
  cinn/backends/llvm/codegen_llvm.cc
  cinn/backends/llvm/codegen_llvm.h
  cinn/common/object.h
  cinn/hlir/framework/graph_compiler.cc
  cinn/hlir/pass/fusion_merge_pass_util.h
  tools/gen_c++_tutorial.py
Labels: contributor, status: proposed

#1462 Op conv2d, softmax support fp64
  cinn/frontend/decomposer/activation.cc
  cinn/hlir/pass/custom_call_pass.cc
  cinn/runtime/cuda/cuda_util.cc
  python/tests/ops/test_conv2d_op.py
  python/tests/ops/test_softmax_op.py
Labels: contributor, status: proposed

#1468 Add Op UnitTest for gelu
  python/tests/ops/test_gelu_op.py
Labels: contributor, status: proposed, HappyOpenSource

#1473 Add op unitest for identity
  python/tests/ops/test_identity_op.py
Labels: contributor, status: proposed, HappyOpenSource
